from config.settings import (
    BME280_ADDR,
    CLIENT_ID,
    CLIENT_REGION,
    DEFAULT_SEND_INTERVAL,
    DHT22_GPIO,
    DISCORD_WEBHOOK_URL,
    SERIAL_BAUDRATE,
    SERIAL_PORT,
    SERIAL_TIMEOUT,
    SERVER_ADDR,
    SERVER_PORT,
)
