from config.settings import (
    SENSOR_DATA_PATH,
    SERVER_ADDR,
    SERVER_PORT,
    TCP_ACCEPT_TIMEOUT_SECONDS,
    TCP_CONNECTION_TIMEOUT_SECONDS,
    TCP_MAX_REQUEST_BYTES,
    TCP_SHUTDOWN_TIMEOUT_SECONDS,
)
